---
name: CI

on:
  push:
    branches: [ "main", "feat/*", "release/*" ]
  pull_request:
    branches: [ "main", "feat/*", "release/*" ]
  schedule:
    - cron: '0 2 * * 1' # https://crontab.guru/#0_2_*_*_1

permissions:
  contents: read

jobs:
  update-linter-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download latest linter rules
        uses: sebastian-sommerfeld-io/github-action-download-common-assets@main
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] refactor: auto-updated linter rules"

  lint-yaml:
    runs-on: ubuntu-latest
    needs: update-linter-rules
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

  lint-env-files:
    runs-on: ubuntu-latest
    needs: update-linter-rules
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run dotenvlinter in container
        run: docker run -i --rm --volume "$(pwd):/app" --workdir "/app" dotenvlinter/dotenv-linter:latest --exclude "*node_modules*" --recursive

  # lint-filenames:
  #   runs-on: ubuntu-latest
  #   needs: update-linter-rules
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run ls-lint in container
  #       run: docker run -i --rm --volume "$(pwd):/data" --workdir "/data" lslintorg/ls-lint:1.11.0

  shellcheck:
    runs-on: ubuntu-latest
    needs: update-linter-rules
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: node_modules target

  angular-cli-lint-dockerfile:
    runs-on: ubuntu-latest
    needs: update-linter-rules
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint > Angular CLI helper
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: components/angular-cli/Dockerfile

  webapp-lint-dockerfile:
    runs-on: ubuntu-latest
    needs: update-linter-rules
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint > Angular CLI helper
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: components/webapp/Dockerfile

  ci-build:
    runs-on: ubuntu-latest
    needs: ['angular-cli-lint-dockerfile', 'webapp-lint-dockerfile']
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker image build - angular-cli
        uses: docker/build-push-action@v3
        with:
          context: ./components/angular-cli
          platforms: linux/amd64
          push: false
          tags: local/angular-cli:dev

      - name: Docker image build - angular-cli
        uses: docker/build-push-action@v3
        with:
          context: ./components/angular-cli
          platforms: linux/amd64
          push: true
          tags: sommerfeldio/gt7-dashboard-webapp:ci-build

  on-failure:
    runs-on: ubuntu-latest
    needs: ['update-linter-rules', 'ci-build', 'lint-yaml', 'lint-env-files', 'shellcheck', 'angular-cli-lint-dockerfile', 'webapp-lint-dockerfile']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
